dist: xenial
language: python
python:
  - "3.6"
  - "3.8"
  - "pypy"
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - python: pypy
addons:
  apt:
    packages:
    - libjpeg-dev
    - python-opencv

install:
  - pip install coveralls
  - make setup

script:
  - make test
after_success:
  coveralls
